[package]
name = "rust-shorten-url"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.16"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.225", features = ["derive"] }
serde-aux = "4.7.0"

[dev-dependencies]
serde_json = "1.0.145"
